/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pwm_pal1.c
**     Project     : rtos_pwm
**     Processor   : S32K144_100
**     Component   : pwm_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-07-28, 19:25, # CodeGen: 4
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file pwm_pal1.c
** @version 01.00
*/         
/*!
**  @addtogroup pwm_pal1_module pwm_pal1 module documentation
**  @{
*/         
#include "pwm_pal1.h"
#include "pwm_pal.h"

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 8.4, external symbol defined without a prior
 * declaration.
 * This symbol is not a part of the public symbols.
 *
 */


/* Timebase */
pwm_ftm_timebase_t pwm_pal1Timebase =
{
    .sourceClock       = FTM_CLOCK_SOURCE_SYSTEMCLK,
    .prescaler         = FTM_CLOCK_DIVID_BY_1,
    .deadtimePrescaler = FTM_DEADTIME_DIVID_BY_1
};
 
 /* Channels */
pwm_channel_t pwm_pal1Channels[1] =
{
    {
        .channel                       = 1,   
        .channelType                   = PWM_EDGE_ALIGNED,      
        .period                        = 5000,
        .duty                          = 2500,
        .polarity                      = PWM_ACTIVE_HIGH,
        .insertDeadtime                = false,
        .deadtime                      = 0,
        .enableComplementaryChannel    = false,
        .complementaryChannelPolarity  = PWM_DUPLICATED,
        .timebase                      = &pwm_pal1Timebase
    },
};
 
 
  /* Initialization configuration */
pwm_global_config_t pwm_pal1Configs =
{
    .pwmChannels          = pwm_pal1Channels,
    .numberOfPwmChannels  = 1,
};
 
  /* Instance configuration */
pwm_instance_t pwm_pal1Instance =
{
    .instType  = PWM_INST_TYPE_FTM,
    .instIdx   = 0,
};
  
 
/* END pwm_pal1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

